require:
  - rubocop-md

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Standard/SemanticBlocks:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false
