name: Lint Docs

on:
  push:
    branches:
    - master
    paths:
    - "**/*.md"
    - ".github/workflows/docs-lint.yml"
    - ".yaspellerrc"
    - ".rubocop-md.yml"
  pull_request:
    paths:
    - "**/*.md"
    - ".github/workflows/docs-lint.yml"
    - ".yaspellerrc"
    - ".rubocop-md.yml"

jobs:
  docs-lint:
    uses: anycable/github-actions/.github/workflows/docs-lint.yml@master
    with:
      mdl-path: "*.md"
      forspell: false
      lychee-args: docs/* --exclude "(assets)/"

  yaspeller:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Yaspeller Action
      uses: heytitle/github-action-yaspeller@v0.0.7
      with:
        ext: "*.md"
        dir: "./docs"
